fix(bins): improve errors when server fails
Example output:
Error: GrpcServer error

Caused by:
    0: transport error
    1: error creating server listener: Address already in use (os error 98)
    2: Address already in use (os error 98

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>